image: maven:latest

cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

variables:
  APP_PATH: /opt/app
  BACKEND_PATH: ${APP_PATH}/myongoingscalendar-backend
  NGINX_PATH: /etc/nginx

stages:
  - build
  - deploy
  - restart

maven-build:
  image: maven:3-jdk-11
  stage: build
  only:
    - master
  script: mvn package spring-boot:repackage
  artifacts:
    paths:
      - target/*.jar

deploy-jar:
  stage: deploy
  only:
    - master
  script:
  - mkdir -p ${BACKEND_PATH}
  - cp -R ./target/* ${BACKEND_PATH}
  tags:
  - shell

deploy-nginx:
  stage: deploy
  only:
    - master
  except:
    variables:
    - $SKIP_NGINX
  script:
  - cp -R ./nginx/maps ${NGINX_PATH}
  - cp -R ./nginx/security ${NGINX_PATH}
  - cp -R ./nginx/proxy ${NGINX_PATH}
  - cp -f ./nginx/nginx.linux.conf ${NGINX_PATH}/conf.d/default.conf
  - cp -f ./nginx/nginx.conf ${NGINX_PATH}/nginx.conf
  tags:
  - shell

restart:
  stage: restart
  only:
  - master
  script:
  - sudo systemctl restart nginx
  - sudo systemctl restart myongoingscalendar
  tags:
  - shell
