image: maven:latest

cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

stages:
  - build
  - deploy
  - restart

maven-build:
  image: maven:3-jdk-8
  stage: build
  only:
    - master
  script: mvn package spring-boot:repackage
  artifacts:
    paths:
      - target/*.jar

deploy-jar:
  stage: deploy
  only:
    - master
  script:
  - mkdir -p /opt/app/myongoingscalendar-backend
  - cp -R ./target/* /opt/app/myongoingscalendar-backend/
  tags:
  - shell

deploy-nginx:
  stage: deploy
  only:
    - master
  script:
  - cp -R ./nginx/maps /etc/nginx
  - cp -R ./nginx/security /etc/nginx
  - cp -f ./nginx/nginx.linux.conf /etc/nginx/conf.d/default.conf
  - cp -f ./nginx/nginx.conf /etc/nginx/nginx.conf
  tags:
  - shell

restart:
  stage: restart
  only:
  - master
  script:
  - sudo systemctl restart nginx
  - sudo systemctl restart myongoingscalendar
  tags:
  - shell
