image: maven:latest

cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

stages:
  - build
  - deploy
  - restart

maven-build:
  image: maven:3-jdk-8
  stage: build
  only:
    - master
  script: mvn verify
  artifacts:
    paths:
      - target/*.jar

deploy-jar:
  stage: deploy
  only:
    - master
  script:
  - mkdir -p /opt/app/myongoingscalendar-backend
  - cp -R ./target/* /opt/app/myongoingscalendar-backend/
  tags:
  - shell

restart:
  stage: restart
  only:
  - master
  script:
  - systemctl restart myongoingscalendar
  tags:
  - shell
