//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.09 at 06:04:04 AM YEKT 
//


package org.myongoingscalendar.model.ANN;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="anime" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="related-prev" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="info" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence minOccurs="0"&gt;
 *                             &lt;element name="img" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                                     &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                           &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ratings" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="nb_votes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                           &lt;attribute name="weighted_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                           &lt;attribute name="bayesian_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="episode" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="title" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                                     &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="review" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="release" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="news" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="staff" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="person" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="cast" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="person" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                           &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="credit" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="company" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="generated-on" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anime"
})
@XmlRootElement(name = "ann")
public class Ann {

    protected Ann.Anime anime;

    /**
     * Gets the value of the anime property.
     *
     * @return
     *     possible object is
     *     {@link Ann.Anime }
     *
     */
    public Ann.Anime getAnime() {
        return anime;
    }

    /**
     * Sets the value of the anime property.
     *
     * @param value
     *     allowed object is
     *     {@link Ann.Anime }
     *
     */
    public void setAnime(Ann.Anime value) {
        this.anime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="related-prev" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="info" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence minOccurs="0"&gt;
     *                   &lt;element name="img" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ratings" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="nb_votes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *                 &lt;attribute name="weighted_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                 &lt;attribute name="bayesian_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="episode" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="title" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *                           &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="review" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="release" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="news" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="staff" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="person" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="cast" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="person" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="credit" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="company" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="generated-on" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relatedPrev",
        "info",
        "ratings",
        "episode",
        "review",
        "release",
        "news",
        "staff",
        "cast",
        "credit"
    })
    public static class Anime {

        @XmlElement(name = "related-prev")
        protected Ann.Anime.RelatedPrev relatedPrev;
        protected List<Ann.Anime.Info> info;
        protected Ann.Anime.Ratings ratings;
        protected List<Ann.Anime.Episode> episode;
        protected List<Ann.Anime.Review> review;
        protected List<Ann.Anime.Release> release;
        protected List<Ann.Anime.News> news;
        protected List<Ann.Anime.Staff> staff;
        protected List<Ann.Anime.Cast> cast;
        protected List<Ann.Anime.Credit> credit;
        @XmlAttribute(name = "id")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer id;
        @XmlAttribute(name = "gid")
        @XmlSchemaType(name = "unsignedInt")
        protected Long gid;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "precision")
        protected String precision;
        @XmlAttribute(name = "generated-on")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar generatedOn;

        /**
         * Gets the value of the relatedPrev property.
         *
         * @return
         *     possible object is
         *     {@link Ann.Anime.RelatedPrev }
         *
         */
        public Ann.Anime.RelatedPrev getRelatedPrev() {
            return relatedPrev;
        }

        /**
         * Sets the value of the relatedPrev property.
         *
         * @param value
         *     allowed object is
         *     {@link Ann.Anime.RelatedPrev }
         *
         */
        public void setRelatedPrev(Ann.Anime.RelatedPrev value) {
            this.relatedPrev = value;
        }

        /**
         * Gets the value of the info property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInfo().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Info }
         *
         *
         */
        public List<Ann.Anime.Info> getInfo() {
            if (info == null) {
                info = new ArrayList<Ann.Anime.Info>();
            }
            return this.info;
        }

        /**
         * Gets the value of the ratings property.
         *
         * @return
         *     possible object is
         *     {@link Ann.Anime.Ratings }
         *
         */
        public Ann.Anime.Ratings getRatings() {
            return ratings;
        }

        /**
         * Sets the value of the ratings property.
         *
         * @param value
         *     allowed object is
         *     {@link Ann.Anime.Ratings }
         *
         */
        public void setRatings(Ann.Anime.Ratings value) {
            this.ratings = value;
        }

        /**
         * Gets the value of the episode property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the episode property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpisode().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Episode }
         *
         *
         */
        public List<Ann.Anime.Episode> getEpisode() {
            if (episode == null) {
                episode = new ArrayList<Ann.Anime.Episode>();
            }
            return this.episode;
        }

        /**
         * Gets the value of the review property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the review property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReview().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Review }
         *
         *
         */
        public List<Ann.Anime.Review> getReview() {
            if (review == null) {
                review = new ArrayList<Ann.Anime.Review>();
            }
            return this.review;
        }

        /**
         * Gets the value of the release property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the release property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelease().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Release }
         *
         *
         */
        public List<Ann.Anime.Release> getRelease() {
            if (release == null) {
                release = new ArrayList<Ann.Anime.Release>();
            }
            return this.release;
        }

        /**
         * Gets the value of the news property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the news property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNews().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.News }
         *
         *
         */
        public List<Ann.Anime.News> getNews() {
            if (news == null) {
                news = new ArrayList<Ann.Anime.News>();
            }
            return this.news;
        }

        /**
         * Gets the value of the staff property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the staff property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStaff().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Staff }
         *
         *
         */
        public List<Ann.Anime.Staff> getStaff() {
            if (staff == null) {
                staff = new ArrayList<Ann.Anime.Staff>();
            }
            return this.staff;
        }

        /**
         * Gets the value of the cast property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cast property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCast().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Cast }
         *
         *
         */
        public List<Ann.Anime.Cast> getCast() {
            if (cast == null) {
                cast = new ArrayList<Ann.Anime.Cast>();
            }
            return this.cast;
        }

        /**
         * Gets the value of the credit property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credit property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredit().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ann.Anime.Credit }
         *
         *
         */
        public List<Ann.Anime.Credit> getCredit() {
            if (credit == null) {
                credit = new ArrayList<Ann.Anime.Credit>();
            }
            return this.credit;
        }

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the gid property.
         *
         * @return
         *     possible object is
         *     {@link Long }
         *
         */
        public Long getGid() {
            return gid;
        }

        /**
         * Sets the value of the gid property.
         *
         * @param value
         *     allowed object is
         *     {@link Long }
         *
         */
        public void setGid(Long value) {
            this.gid = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the precision property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPrecision() {
            return precision;
        }

        /**
         * Sets the value of the precision property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPrecision(String value) {
            this.precision = value;
        }

        /**
         * Gets the value of the generatedOn property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getGeneratedOn() {
            return generatedOn;
        }

        /**
         * Sets the value of the generatedOn property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setGeneratedOn(XMLGregorianCalendar value) {
            this.generatedOn = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="person" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "role",
            "person"
        })
        public static class Cast {

            protected String role;
            protected Ann.Anime.Cast.Person person;
            @XmlAttribute(name = "gid")
            @XmlSchemaType(name = "unsignedInt")
            protected Long gid;
            @XmlAttribute(name = "lang")
            protected String lang;

            /**
             * Gets the value of the role property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRole() {
                return role;
            }

            /**
             * Sets the value of the role property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRole(String value) {
                this.role = value;
            }

            /**
             * Gets the value of the person property.
             *
             * @return
             *     possible object is
             *     {@link Ann.Anime.Cast.Person }
             *
             */
            public Ann.Anime.Cast.Person getPerson() {
                return person;
            }

            /**
             * Sets the value of the person property.
             *
             * @param value
             *     allowed object is
             *     {@link Ann.Anime.Cast.Person }
             *
             */
            public void setPerson(Ann.Anime.Cast.Person value) {
                this.person = value;
            }

            /**
             * Gets the value of the gid property.
             *
             * @return
             *     possible object is
             *     {@link Long }
             *
             */
            public Long getGid() {
                return gid;
            }

            /**
             * Sets the value of the gid property.
             *
             * @param value
             *     allowed object is
             *     {@link Long }
             *
             */
            public void setGid(Long value) {
                this.gid = value;
            }

            /**
             * Gets the value of the lang property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLang(String value) {
                this.lang = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Person {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id")
                @XmlSchemaType(name = "unsignedShort")
                protected Integer id;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *
                 */
                public Integer getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *
                 */
                public void setId(Integer value) {
                    this.id = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="company" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "task",
            "company"
        })
        public static class Credit {

            protected String task;
            protected Ann.Anime.Credit.Company company;
            @XmlAttribute(name = "gid")
            @XmlSchemaType(name = "unsignedInt")
            protected Long gid;

            /**
             * Gets the value of the task property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTask() {
                return task;
            }

            /**
             * Sets the value of the task property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTask(String value) {
                this.task = value;
            }

            /**
             * Gets the value of the company property.
             *
             * @return
             *     possible object is
             *     {@link Ann.Anime.Credit.Company }
             *
             */
            public Ann.Anime.Credit.Company getCompany() {
                return company;
            }

            /**
             * Sets the value of the company property.
             *
             * @param value
             *     allowed object is
             *     {@link Ann.Anime.Credit.Company }
             *
             */
            public void setCompany(Ann.Anime.Credit.Company value) {
                this.company = value;
            }

            /**
             * Gets the value of the gid property.
             *
             * @return
             *     possible object is
             *     {@link Long }
             *
             */
            public Long getGid() {
                return gid;
            }

            /**
             * Sets the value of the gid property.
             *
             * @param value
             *     allowed object is
             *     {@link Long }
             *
             */
            public void setGid(Long value) {
                this.gid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Company {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id")
                @XmlSchemaType(name = "unsignedShort")
                protected Integer id;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *
                 */
                public Integer getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *
                 */
                public void setId(Integer value) {
                    this.id = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="title" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title"
        })
        public static class Episode {

            protected Ann.Anime.Episode.Title title;
            @XmlAttribute(name = "num")
            @XmlSchemaType(name = "unsignedByte")
            protected Short num;

            /**
             * Gets the value of the title property.
             *
             * @return
             *     possible object is
             *     {@link Ann.Anime.Episode.Title }
             *
             */
            public Ann.Anime.Episode.Title getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             *
             * @param value
             *     allowed object is
             *     {@link Ann.Anime.Episode.Title }
             *
             */
            public void setTitle(Ann.Anime.Episode.Title value) {
                this.title = value;
            }

            /**
             * Gets the value of the num property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setNum(Short value) {
                this.num = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
             *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Title {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "gid")
                @XmlSchemaType(name = "unsignedInt")
                protected Long gid;
                @XmlAttribute(name = "lang")
                protected String lang;

                /**
                 * Gets the value of the value property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the gid property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *
                 */
                public Long getGid() {
                    return gid;
                }

                /**
                 * Sets the value of the gid property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *
                 */
                public void setGid(Long value) {
                    this.gid = value;
                }

                /**
                 * Gets the value of the lang property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getLang() {
                    return lang;
                }

                /**
                 * Sets the value of the lang property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setLang(String value) {
                    this.lang = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence minOccurs="0"&gt;
         *         &lt;element name="img" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Info {

            @XmlElementRef(name = "img", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;
            @XmlAttribute(name = "gid")
            @XmlSchemaType(name = "unsignedInt")
            protected Long gid;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "src")
            protected String src;
            @XmlAttribute(name = "width")
            @XmlSchemaType(name = "unsignedByte")
            protected Short width;
            @XmlAttribute(name = "height")
            @XmlSchemaType(name = "unsignedByte")
            protected Short height;
            @XmlAttribute(name = "lang")
            protected String lang;
            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link Ann.Anime.Info.Img }{@code >}
             * {@link String }
             *
             *
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

            /**
             * Gets the value of the gid property.
             *
             * @return
             *     possible object is
             *     {@link Long }
             *
             */
            public Long getGid() {
                return gid;
            }

            /**
             * Sets the value of the gid property.
             *
             * @param value
             *     allowed object is
             *     {@link Long }
             *
             */
            public void setGid(Long value) {
                this.gid = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the src property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSrc() {
                return src;
            }

            /**
             * Sets the value of the src property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSrc(String value) {
                this.src = value;
            }

            /**
             * Gets the value of the width property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setWidth(Short value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             *
             * @return
             *     possible object is
             *     {@link Short }
             *
             */
            public Short getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             *
             * @param value
             *     allowed object is
             *     {@link Short }
             *
             */
            public void setHeight(Short value) {
                this.height = value;
            }

            /**
             * Gets the value of the lang property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLang(String value) {
                this.lang = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
             *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Img {

                @XmlAttribute(name = "src")
                protected String src;
                @XmlAttribute(name = "width")
                @XmlSchemaType(name = "unsignedByte")
                protected Short width;
                @XmlAttribute(name = "height")
                @XmlSchemaType(name = "unsignedByte")
                protected Short height;

                /**
                 * Gets the value of the src property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getSrc() {
                    return src;
                }

                /**
                 * Sets the value of the src property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setSrc(String value) {
                    this.src = value;
                }

                /**
                 * Gets the value of the width property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *
                 */
                public Short getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *
                 */
                public void setWidth(Short value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *
                 */
                public Short getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *
                 */
                public void setHeight(Short value) {
                    this.height = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class News {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "datetime")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar datetime;
            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the datetime property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getDatetime() {
                return datetime;
            }

            /**
             * Sets the value of the datetime property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setDatetime(XMLGregorianCalendar value) {
                this.datetime = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="nb_votes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *       &lt;attribute name="weighted_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *       &lt;attribute name="bayesian_score" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Ratings {

            @XmlAttribute(name = "nb_votes")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer nbVotes;
            @XmlAttribute(name = "weighted_score")
            protected BigDecimal weightedScore;
            @XmlAttribute(name = "bayesian_score")
            protected BigDecimal bayesianScore;

            /**
             * Gets the value of the nbVotes property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getNbVotes() {
                return nbVotes;
            }

            /**
             * Sets the value of the nbVotes property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setNbVotes(Integer value) {
                this.nbVotes = value;
            }

            /**
             * Gets the value of the weightedScore property.
             *
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *
             */
            public BigDecimal getWeightedScore() {
                return weightedScore;
            }

            /**
             * Sets the value of the weightedScore property.
             *
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *
             */
            public void setWeightedScore(BigDecimal value) {
                this.weightedScore = value;
            }

            /**
             * Gets the value of the bayesianScore property.
             *
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *
             */
            public BigDecimal getBayesianScore() {
                return bayesianScore;
            }

            /**
             * Sets the value of the bayesianScore property.
             *
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *
             */
            public void setBayesianScore(BigDecimal value) {
                this.bayesianScore = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RelatedPrev {

            @XmlAttribute(name = "rel")
            protected String rel;
            @XmlAttribute(name = "id")
            @XmlSchemaType(name = "unsignedShort")
            protected Integer id;

            /**
             * Gets the value of the rel property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRel() {
                return rel;
            }

            /**
             * Sets the value of the rel property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRel(String value) {
                this.rel = value;
            }

            /**
             * Gets the value of the id property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setId(Integer value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Release {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "date")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar date;
            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the date property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setDate(XMLGregorianCalendar value) {
                this.date = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Review {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "href")
            protected String href;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="person" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "task",
            "person"
        })
        public static class Staff {

            protected String task;
            protected Ann.Anime.Staff.Person person;
            @XmlAttribute(name = "gid")
            @XmlSchemaType(name = "unsignedInt")
            protected Long gid;

            /**
             * Gets the value of the task property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTask() {
                return task;
            }

            /**
             * Sets the value of the task property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTask(String value) {
                this.task = value;
            }

            /**
             * Gets the value of the person property.
             *
             * @return
             *     possible object is
             *     {@link Ann.Anime.Staff.Person }
             *
             */
            public Ann.Anime.Staff.Person getPerson() {
                return person;
            }

            /**
             * Sets the value of the person property.
             *
             * @param value
             *     allowed object is
             *     {@link Ann.Anime.Staff.Person }
             *
             */
            public void setPerson(Ann.Anime.Staff.Person value) {
                this.person = value;
            }

            /**
             * Gets the value of the gid property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getGid() {
                return gid;
            }

            /**
             * Sets the value of the gid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setGid(Long value) {
                this.gid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Person {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id")
                @XmlSchemaType(name = "unsignedInt")
                protected Long id;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public Long getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setId(Long value) {
                    this.id = value;
                }

            }

        }

    }

}
