//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.09 at 06:04:04 AM YEKT 
//


package org.myongoingscalendar.model.ANN;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnnAnimeInfoImg_QNAME = new QName("", "img");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ann }
     *
     */
    public Ann createAnn() {
        return new Ann();
    }

    /**
     * Create an instance of {@link Ann.Anime }
     *
     */
    public Ann.Anime createAnnAnime() {
        return new Ann.Anime();
    }

    /**
     * Create an instance of {@link Ann.Anime.Credit }
     *
     */
    public Ann.Anime.Credit createAnnAnimeCredit() {
        return new Ann.Anime.Credit();
    }

    /**
     * Create an instance of {@link Ann.Anime.Cast }
     *
     */
    public Ann.Anime.Cast createAnnAnimeCast() {
        return new Ann.Anime.Cast();
    }

    /**
     * Create an instance of {@link Ann.Anime.Staff }
     *
     */
    public Ann.Anime.Staff createAnnAnimeStaff() {
        return new Ann.Anime.Staff();
    }

    /**
     * Create an instance of {@link Ann.Anime.Episode }
     *
     */
    public Ann.Anime.Episode createAnnAnimeEpisode() {
        return new Ann.Anime.Episode();
    }

    /**
     * Create an instance of {@link Ann.Anime.Info }
     *
     */
    public Ann.Anime.Info createAnnAnimeInfo() {
        return new Ann.Anime.Info();
    }

    /**
     * Create an instance of {@link Ann.Anime.RelatedPrev }
     *
     */
    public Ann.Anime.RelatedPrev createAnnAnimeRelatedPrev() {
        return new Ann.Anime.RelatedPrev();
    }

    /**
     * Create an instance of {@link Ann.Anime.Ratings }
     *
     */
    public Ann.Anime.Ratings createAnnAnimeRatings() {
        return new Ann.Anime.Ratings();
    }

    /**
     * Create an instance of {@link Ann.Anime.Review }
     *
     */
    public Ann.Anime.Review createAnnAnimeReview() {
        return new Ann.Anime.Review();
    }

    /**
     * Create an instance of {@link Ann.Anime.Release }
     *
     */
    public Ann.Anime.Release createAnnAnimeRelease() {
        return new Ann.Anime.Release();
    }

    /**
     * Create an instance of {@link Ann.Anime.News }
     *
     */
    public Ann.Anime.News createAnnAnimeNews() {
        return new Ann.Anime.News();
    }

    /**
     * Create an instance of {@link Ann.Anime.Credit.Company }
     *
     */
    public Ann.Anime.Credit.Company createAnnAnimeCreditCompany() {
        return new Ann.Anime.Credit.Company();
    }

    /**
     * Create an instance of {@link Ann.Anime.Cast.Person }
     *
     */
    public Ann.Anime.Cast.Person createAnnAnimeCastPerson() {
        return new Ann.Anime.Cast.Person();
    }

    /**
     * Create an instance of {@link Ann.Anime.Staff.Person }
     *
     */
    public Ann.Anime.Staff.Person createAnnAnimeStaffPerson() {
        return new Ann.Anime.Staff.Person();
    }

    /**
     * Create an instance of {@link Ann.Anime.Episode.Title }
     *
     */
    public Ann.Anime.Episode.Title createAnnAnimeEpisodeTitle() {
        return new Ann.Anime.Episode.Title();
    }

    /**
     * Create an instance of {@link Ann.Anime.Info.Img }
     *
     */
    public Ann.Anime.Info.Img createAnnAnimeInfoImg() {
        return new Ann.Anime.Info.Img();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ann.Anime.Info.Img }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ann.Anime.Info.Img }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "img", scope = Ann.Anime.Info.class)
    public JAXBElement<Ann.Anime.Info.Img> createAnnAnimeInfoImg(Ann.Anime.Info.Img value) {
        return new JAXBElement<Ann.Anime.Info.Img>(_AnnAnimeInfoImg_QNAME, Ann.Anime.Info.Img.class, Ann.Anime.Info.class, value);
    }

}
